#ifndef MOCKOTO_CHIBI_C_GEN_HPP
#define MOCKOTO_CHIBI_C_GEN_HPP

#include "clang/AST/AST.h"
#include "clang/AST/ASTConsumer.h"
#include "clang/AST/RecursiveASTVisitor.h"
#include "clang/Frontend/CompilerInstance.h"
#include "clang/Frontend/FrontendAction.h"
#include "clang/Tooling/Tooling.h"

#include <algorithm>
#include <cctype>
#include <cstring>
#include <cstdlib>
#include <set>
#include <string>
#include <vector>

#include "Config.hpp"

using namespace clang;

namespace mockoto {

class ChibiCGenVisitor : public RecursiveASTVisitor<ChibiCGenVisitor> {
  ASTContext *Context;
  mockoto::Config Config;
  llvm::StringRef InFile;
  std::set<std::string> emitted;
  std::vector<std::string> foreignRegistrations;
  std::vector<std::string> hookDispatches;
  std::vector<std::string> constantDefinitions;

public:
  explicit ChibiCGenVisitor(ASTContext *Context, mockoto::Config Config,
                            llvm::StringRef InFile)
      : Context(Context), Config(Config), InFile(InFile) {
    llvm::outs() << autogeneratedWarning("//") << "\n";
    llvm::outs() << "#include <stdint.h>\n";
    llvm::outs() << "#include <stddef.h>\n";
    llvm::outs() << "#include <string.h>\n";
    llvm::outs() << "#include <stdlib.h>\n";
    llvm::outs() << "#include <chibi/eval.h>\n";
    for (auto inFile : Config.includeFiles)
      llvm::outs() << "#include \"" << inFile << "\"\n";
    llvm::outs() << R"c(

static sexp mockoto_chibi_ctx = SEXP_FALSE;

static __attribute__((unused)) sexp mockoto_chibi_lookup_proc(sexp ctx, const char *name) {
  return sexp_eval_string(ctx, name, -1, NULL);
}

static __attribute__((unused)) sexp mockoto_chibi_u8_list(sexp ctx, const uint8_t *data, size_t len) {
  sexp out = SEXP_NULL;
  size_t i = len;
  while (i > 0) {
    --i;
    out = sexp_cons(ctx, sexp_make_unsigned_integer(ctx, data[i]), out);
  }
  return out;
}

static __attribute__((unused)) sexp mockoto_chibi_cpointer(sexp ctx, void *ptr) {
  if (!ptr)
    return SEXP_FALSE;
  return sexp_make_cpointer(ctx, SEXP_CPOINTER, ptr, SEXP_FALSE, 0);
}

static sexp
sexp_u8make_stub(sexp ctx, sexp self, sexp_sint_t n)
{
  uint8_t *ptr = (uint8_t *)calloc(1, sizeof(uint8_t));
  if (!ptr)
    return sexp_xtype_exception(ctx, self, "u8make: allocation failed", SEXP_FALSE);
  return sexp_make_cpointer(ctx, SEXP_CPOINTER, ptr, SEXP_FALSE, 1);
}

static sexp
sexp_u8read_stub(sexp ctx, sexp self, sexp_sint_t n, sexp arg0)
{
  if (!sexp_cpointerp(arg0) && !sexp_not(arg0))
    return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg0);
  uint8_t *ptr = (uint8_t *)sexp_cpointer_maybe_null_value(arg0);
  return sexp_make_unsigned_integer(ctx, ptr ? *ptr : 0);
}

static sexp
sexp_u8write_stub(sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1)
{
  if (!sexp_cpointerp(arg0) && !sexp_not(arg0))
    return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg0);
  if (!sexp_exact_integerp(arg1))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg1);
  uint8_t *ptr = (uint8_t *)sexp_cpointer_maybe_null_value(arg0);
  if (ptr)
    *ptr = (uint8_t)sexp_uint_value(arg1);
  return SEXP_VOID;
}

)c";
  }

  ~ChibiCGenVisitor() {
    llvm::outs() << R"c(
static sexp
sexp_mockoto_mock_stub(sexp ctx, sexp self, sexp_sint_t n, sexp hook_name,
                       sexp proc_name)
{
  if (!sexp_stringp(hook_name))
    return sexp_type_exception(ctx, self, SEXP_STRING, hook_name);
  if (!sexp_stringp(proc_name) && !sexp_not(proc_name))
    return sexp_type_exception(ctx, self, SEXP_STRING, proc_name);
  mockoto_chibi_ctx = ctx;
  const char *hook __attribute__((unused)) = sexp_string_data(hook_name);
)c";
    for (const auto &s : hookDispatches)
      llvm::outs() << s;
    llvm::outs() << R"c(
  return sexp_xtype_exception(ctx, self, "unknown mock hook", hook_name);
}

)c";
    llvm::outs() << R"c(
sexp
sexp_init_library(sexp ctx, sexp self, sexp_sint_t n, sexp env,
                  const char *version, const sexp_abi_identifier_t abi)
{
  sexp op = SEXP_FALSE;
  if (!(sexp_version_compatible(ctx, version, sexp_version) &&
        sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return SEXP_ABI_ERROR;

  mockoto_chibi_ctx = ctx;
)c";
    for (const auto &s : foreignRegistrations)
      llvm::outs() << s;
    for (const auto &s : constantDefinitions)
      llvm::outs() << s;
    llvm::outs() << "  op = sexp_define_foreign(ctx, env, \"mockoto_mock\", 2, "
                    "sexp_mockoto_mock_stub);\n";
    llvm::outs() << "  if (sexp_opcodep(op)) {\n";
    llvm::outs() << "    sexp_opcode_return_type(op) = SEXP_VOID;\n";
    llvm::outs() << "    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);\n";
    llvm::outs() << "    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_STRING);\n";
    llvm::outs() << "  }\n";
    llvm::outs() << "  op = sexp_define_foreign(ctx, env, \"u8make\", 0, "
                    "sexp_u8make_stub);\n";
    llvm::outs() << "  if (sexp_opcodep(op)) {\n";
    llvm::outs() << "    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_CPOINTER);\n";
    llvm::outs() << "  }\n";
    llvm::outs() << "  op = sexp_define_foreign(ctx, env, \"u8read\", 1, "
                    "sexp_u8read_stub);\n";
    llvm::outs() << "  if (sexp_opcodep(op)) {\n";
    llvm::outs() << "    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);\n";
    llvm::outs() << "    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_CPOINTER);\n";
    llvm::outs() << "  }\n";
    llvm::outs() << "  op = sexp_define_foreign(ctx, env, \"u8write!\", 2, "
                    "sexp_u8write_stub);\n";
    llvm::outs() << "  if (sexp_opcodep(op)) {\n";
    llvm::outs() << "    sexp_opcode_return_type(op) = SEXP_VOID;\n";
    llvm::outs() << "    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_CPOINTER);\n";
    llvm::outs() << "    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FIXNUM);\n";
    llvm::outs() << "  }\n";
    llvm::outs() << "\n  return SEXP_VOID;\n}\n";
  }

  bool VisitNamedDecl(NamedDecl *NamedDecl) {
    if (!shouldProcess(NamedDecl))
      return true;

    const FunctionDecl *fdecl = dyn_cast<FunctionDecl>(NamedDecl);
    if (fdecl) {
      emitFunction(fdecl);
      return true;
    }

    const RecordDecl *rdecl = dyn_cast<RecordDecl>(NamedDecl);
    if (rdecl) {
      emitRecordHelpers(rdecl);
      return true;
    }

    const EnumDecl *edecl = dyn_cast<EnumDecl>(NamedDecl);
    if (edecl) {
      emitEnumConstants(edecl);
      return true;
    }
    return true;
  }

private:
  static bool endsWith(const std::string &s, const std::string &suffix) {
    if (suffix.size() > s.size())
      return false;
    return std::equal(suffix.rbegin(), suffix.rend(), s.rbegin());
  }

  bool shouldProcess(const NamedDecl *decl) const {
    SourceManager &sm = Context->getSourceManager();
    SourceLocation loc = sm.getExpansionLoc(decl->getLocation());
    if (!loc.isValid())
      return false;

    std::string path = sm.getFilename(loc).str();
    if (path.empty())
      return false;

    for (auto pfx : Config.excludePatterns)
      if (path.find(pfx) != std::string::npos)
        return false;

    if (Config.includeFiles.empty())
      return true;

    for (auto h : Config.includeFiles) {
      if (path == h)
        return true;
      if (endsWith(path, "/" + h))
        return true;
      if (endsWith(path, h))
        return true;
      size_t slash = h.find_last_of("/\\");
      if (slash != std::string::npos) {
        std::string base = h.substr(slash + 1);
        if (!base.empty() && endsWith(path, "/" + base))
          return true;
      }
    }
    return false;
  }

  static std::string toSymbol(const std::string &raw) {
    if (raw.empty())
      return "anon";
    std::string out;
    out.reserve(raw.size());
    for (unsigned char c : raw) {
      if (std::isalnum(c) || c == '_')
        out.push_back((char)c);
      else
        out.push_back('_');
    }
    if (!out.empty() && std::isdigit((unsigned char)out[0]))
      out = "t_" + out;
    return out;
  }

  static std::string encodeSyntheticName(const std::string &raw) {
    static const char *hex = "0123456789abcdef";
    std::string out;
    out.reserve(raw.size() * 4);
    for (unsigned char c : raw) {
      if (std::isalnum(c) || c == '_') {
        out.push_back((char)c);
        continue;
      }
      out += "_X";
      out.push_back(hex[(c >> 4) & 0x0f]);
      out.push_back(hex[c & 0x0f]);
    }
    if (!out.empty() && std::isdigit((unsigned char)out[0]))
      out = "t_" + out;
    return out;
  }

  static std::string syntheticSchemeName(const std::string &recordName,
                                         const std::string &suffix) {
    return recordName + "-" + suffix;
  }

  std::string cEnumType(const EnumDecl *decl) const {
    if (const TypedefNameDecl *typedefDecl = decl->getTypedefNameForAnonDecl())
      return typedefDecl->getNameAsString();
    return "enum " + decl->getQualifiedNameAsString();
  }

  std::string cType(QualType type) const {
    type = canonicalType(type);
    if (const EnumType *et = type->getAs<EnumType>())
      return cEnumType(et->getDecl());
    PrintingPolicy pp(Context->getLangOpts());
    pp.adjustForCPlusPlus();
    pp.SuppressTagKeyword = false;
    return type.getAsString(pp);
  }

  std::string cRecordType(const RecordDecl *decl) const {
    if (const TypedefNameDecl *typedefDecl = decl->getTypedefNameForAnonDecl())
      return typedefDecl->getNameAsString();

    std::string kind;
    if (decl->isStruct())
      kind = "struct ";
    else if (decl->isUnion())
      kind = "union ";
    else if (decl->isClass())
      kind = "class ";

    return kind + decl->getQualifiedNameAsString();
  }

  QualType canonicalType(QualType type) const {
    type = type.getDesugaredType(*Context);
    type.removeLocalFastQualifiers();
    if (const ElaboratedType *et = dyn_cast<ElaboratedType>(type.getTypePtr()))
      return canonicalType(et->getNamedType());
    return type;
  }

  bool isVoid(QualType type) const { return canonicalType(type)->isVoidType(); }

  bool isBool(QualType type) const {
    type = canonicalType(type);
    if (const BuiltinType *bt = dyn_cast<BuiltinType>(type.getTypePtr()))
      return bt->getKind() == BuiltinType::Bool;
    return false;
  }

  bool isIntegerLike(QualType type) const {
    type = canonicalType(type);
    return isBool(type) || type->isIntegerType() || type->isEnumeralType();
  }

  bool isUnsignedIntegerLike(QualType type) const {
    type = canonicalType(type);
    return type->isUnsignedIntegerType();
  }

  bool isCString(QualType type) const {
    type = canonicalType(type);
    if (!type->isPointerType())
      return false;
    QualType p = canonicalType(type->getPointeeType());
    if (const BuiltinType *bt = dyn_cast<BuiltinType>(p.getTypePtr()))
      return bt->getKind() == BuiltinType::Char_S ||
             bt->getKind() == BuiltinType::Char_U;
    return false;
  }

  bool isByteBufferPointer(QualType type) const {
    type = canonicalType(type);
    if (!type->isPointerType())
      return false;
    QualType p = canonicalType(type->getPointeeType());
    if (const BuiltinType *bt = dyn_cast<BuiltinType>(p.getTypePtr()))
      return bt->getKind() == BuiltinType::UChar ||
             bt->getKind() == BuiltinType::SChar;
    return false;
  }

  bool isOutScalarPointer(QualType type) const {
    type = canonicalType(type);
    if (!type->isPointerType())
      return false;
    QualType p = type->getPointeeType();
    if (p.isConstQualified())
      return false;
    p = canonicalType(p);
    return isIntegerLike(p);
  }

  bool isSupportedPointer(QualType type) const {
    type = canonicalType(type);
    return type->isPointerType();
  }

  bool isSupportedFieldType(QualType type) const {
    type = canonicalType(type);
    return isBool(type) || isIntegerLike(type) || isCString(type) ||
           isSupportedPointer(type);
  }

  const FunctionProtoType *asFunctionProto(QualType type) const {
    type = canonicalType(type);
    if (const FunctionProtoType *ft = type->getAs<FunctionProtoType>())
      return ft;
    if (type->isFunctionPointerType())
      return type->getPointeeType()->getAs<FunctionProtoType>();
    return NULL;
  }

  const FunctionType *asFunctionType(QualType type) const {
    type = canonicalType(type);
    if (const FunctionType *ft = type->getAs<FunctionType>())
      return ft;
    if (type->isFunctionPointerType())
      return type->getPointeeType()->getAs<FunctionType>();
    return NULL;
  }

  std::string schemeTypeIdExpr(QualType type) const {
    type = canonicalType(type);
    if (isVoid(type))
      return "SEXP_VOID";
    if (isBool(type))
      return "sexp_make_fixnum(SEXP_BOOLEAN)";
    if (isIntegerLike(type))
      return "sexp_make_fixnum(SEXP_FIXNUM)";
    if (isCString(type))
      return "sexp_make_fixnum(SEXP_STRING)";
    if (isByteBufferPointer(type))
      return "sexp_make_fixnum(SEXP_BYTES)";
    if (isSupportedPointer(type))
      return "sexp_make_fixnum(SEXP_CPOINTER)";
    return "sexp_make_fixnum(SEXP_OBJECT)";
  }

  bool canEmitDirectWrapper(const FunctionDecl *decl) const {
    const FunctionProtoType *ft = decl->getType()->getAs<FunctionProtoType>();
    if (!ft)
      return false;
    if (!isVoid(ft->getReturnType()) && !isIntegerLike(ft->getReturnType()) &&
        !isCString(ft->getReturnType()) &&
        !isSupportedPointer(ft->getReturnType()))
      return false;

    for (unsigned i = 0; i < ft->getNumParams(); ++i) {
      QualType pt = ft->getParamType(i);
      if (pt->isFunctionPointerType() || pt->isFunctionType())
        return false;
      if (!isVoid(pt) && !isIntegerLike(pt) && !isCString(pt) &&
          !isSupportedPointer(pt))
        return false;
    }
    return true;
  }

  int findLengthParamIndex(const FunctionDecl *decl, unsigned pointerIndex) const {
    const FunctionProtoType *ft = decl->getType()->getAs<FunctionProtoType>();
    if (!ft)
      return -1;
    for (unsigned i = pointerIndex + 1; i < ft->getNumParams(); ++i) {
      const ParmVarDecl *pdecl = decl->getParamDecl(i);
      std::string pname = pdecl ? pdecl->getNameAsString() : "";
      if (!pname.empty() &&
          (pname == "len" || pname == "size" || pname == "count" ||
           pname == "n") &&
          isIntegerLike(ft->getParamType(i)))
        return (int)i;
    }
    return -1;
  }

  std::string defaultReturnExpr(QualType type) const {
    if (isVoid(type))
      return "";
    if (isSupportedPointer(type))
      return "NULL";
    if (isBool(type))
      return "0";
    if (isIntegerLike(type))
      return "0";
    return "0";
  }

  std::string fromSexpExpr(QualType type, const std::string &expr) const {
    type = canonicalType(type);
    if (isBool(type))
      return "(" + cType(type) + ")(!sexp_not(" + expr + "))";
    if (isIntegerLike(type)) {
      if (isUnsignedIntegerLike(type))
        return "(" + cType(type) + ")sexp_uint_value(" + expr + ")";
      return "(" + cType(type) + ")sexp_sint_value(" + expr + ")";
    }
    if (isCString(type))
      return "(" + cType(type) + ")sexp_string_maybe_null_data(" + expr + ")";
    if (isSupportedPointer(type))
      return "(" + cType(type) + ")sexp_cpointer_maybe_null_value(" + expr +
             ")";
    return "(" + cType(type) + ")0";
  }

  std::string toSexpExpr(QualType type, const std::string &expr) const {
    type = canonicalType(type);
    if (isVoid(type))
      return "SEXP_VOID";
    if (isBool(type))
      return "((" + expr + ") ? SEXP_TRUE : SEXP_FALSE)";
    if (isIntegerLike(type)) {
      if (isUnsignedIntegerLike(type))
        return "sexp_make_unsigned_integer(ctx, " + expr + ")";
      return "sexp_make_integer(ctx, " + expr + ")";
    }
    if (isCString(type))
      return "(" + expr + " ? sexp_c_string(ctx, " + expr + ", -1) : SEXP_FALSE)";
    if (isSupportedPointer(type))
      return "mockoto_chibi_cpointer(ctx, (void *)" + expr + ")";
    return "SEXP_VOID";
  }

  std::string hookArgToSexpExpr(const FunctionProtoType *cbType,
                                const std::vector<int> &lengthParamIndex,
                                unsigned index,
                                const std::string &name) const {
    QualType type = cbType->getParamType(index);
    type = canonicalType(type);
    if (isBool(type))
      return "(" + name + " ? SEXP_TRUE : SEXP_FALSE)";
    if (isIntegerLike(type)) {
      if (isUnsignedIntegerLike(type))
        return "sexp_make_unsigned_integer(mockoto_chibi_ctx, " + name + ")";
      return "sexp_make_integer(mockoto_chibi_ctx, " + name + ")";
    }
    if (isCString(type))
      return "(" + name + " ? sexp_c_string(mockoto_chibi_ctx, " + name +
             ", -1) : SEXP_FALSE)";
    if (isByteBufferPointer(type)) {
      int lenIndex = lengthParamIndex[index];
      if (lenIndex >= 0)
        return "mockoto_chibi_u8_list(mockoto_chibi_ctx, (const uint8_t *)" +
               name + ", (size_t)__param_" + std::to_string(lenIndex) + ")";
    }
    return "mockoto_chibi_cpointer(mockoto_chibi_ctx, (void *)" + name + ")";
  }

  void emitFunction(const FunctionDecl *decl) {
    if (!decl->hasPrototype())
      return;
    if (!Config.includeStaticFunctions && decl->getStorageClass() == SC_Static)
      return;

    std::string name = toSymbol(decl->getQualifiedNameAsString());
    if (emitted.find(name) != emitted.end())
      return;
    emitted.insert(name);

    const FunctionProtoType *ft = decl->getType()->getAs<FunctionProtoType>();
    if (!ft)
      return;

    if (ft->getNumParams() == 1 && asFunctionType(ft->getParamType(0)) &&
        isVoid(ft->getReturnType())) {
      emitHookSetter(decl, name, asFunctionType(ft->getParamType(0)));
    } else if (canEmitDirectWrapper(decl)) {
      emitDirectWrapper(decl, name);
    }
  }

  void emitRecordHelpers(const RecordDecl *decl) {
    if (!decl->isCompleteDefinition() || decl->getName().empty())
      return;

    std::string recordName = toSymbol(decl->getQualifiedNameAsString());
    std::string emittedKey = "record:" + recordName;
    if (emitted.find(emittedKey) != emitted.end())
      return;
    emitted.insert(emittedKey);

    std::string recordType = cRecordType(decl);

    std::string makeName = syntheticSchemeName(recordName, "make");
    std::string makeStubName = encodeSyntheticName(makeName);
    std::string destroyName = syntheticSchemeName(recordName, "destroy");
    std::string destroyStubName = encodeSyntheticName(destroyName);

    llvm::outs() << "static sexp\nsexp_" << makeStubName
                 << "_make_stub(sexp ctx, sexp self, sexp_sint_t n)\n{\n";
    llvm::outs() << "  " << recordType << " *ptr = (" << recordType
                 << " *)calloc(1, sizeof(" << recordType << "));\n";
    llvm::outs() << "  if (!ptr)\n";
    llvm::outs() << "    return sexp_xtype_exception(ctx, self, \""
                 << makeName << ": allocation failed\", SEXP_FALSE);\n";
    llvm::outs() << "  return sexp_make_cpointer(ctx, SEXP_CPOINTER, ptr, "
                    "SEXP_FALSE, 1);\n";
    llvm::outs() << "}\n\n";
    appendForeignRegistration(makeName, makeStubName + "_make",
                              "sexp_make_fixnum(SEXP_CPOINTER)", {});

    llvm::outs() << "static sexp\nsexp_" << destroyStubName
                 << "_destroy_stub(sexp ctx, sexp self, sexp_sint_t n, sexp arg0)\n{\n";
    llvm::outs() << "  if (!sexp_cpointerp(arg0) && !sexp_not(arg0))\n";
    llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg0);\n";
    llvm::outs() << "  free((" << recordType
                 << " *)sexp_cpointer_maybe_null_value(arg0));\n";
    llvm::outs() << "  return SEXP_VOID;\n";
    llvm::outs() << "}\n\n";
    appendForeignRegistration(destroyName, destroyStubName + "_destroy", "SEXP_VOID",
                              {"sexp_make_fixnum(SEXP_CPOINTER)"});

    for (const FieldDecl *field : decl->fields()) {
      if (!field || field->getName().empty())
        continue;
      QualType fieldType = canonicalType(field->getType());
      if (!isSupportedFieldType(fieldType))
        continue;
      std::string fieldName = toSymbol(field->getNameAsString());
      std::string readerName = syntheticSchemeName(recordName, fieldName);
      std::string readerStubName = encodeSyntheticName(readerName);
      std::string fieldExpr = "ptr->" + field->getNameAsString();

      llvm::outs() << "static sexp\nsexp_" << readerStubName
                   << "_stub(sexp ctx, sexp self, sexp_sint_t n, sexp arg0)\n{\n";
      llvm::outs() << "  if (!sexp_cpointerp(arg0) && !sexp_not(arg0))\n";
      llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg0);\n";
      llvm::outs() << "  " << recordType << " *ptr = (" << recordType
                   << " *)sexp_cpointer_maybe_null_value(arg0);\n";
      llvm::outs() << "  return " << toSexpExpr(fieldType, "ptr ? " + fieldExpr + " : (" + cType(fieldType) + ")0")
                   << ";\n";
      llvm::outs() << "}\n\n";
      appendForeignRegistration(readerName, readerStubName, schemeTypeIdExpr(fieldType),
                                {"sexp_make_fixnum(SEXP_CPOINTER)"});

      if (field->getType().isConstQualified())
        continue;

      std::string writerName = readerName + "!";
      std::string writerStubName = readerStubName + "_set";
      llvm::outs() << "static sexp\nsexp_" << writerStubName
                   << "_stub(sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1)\n{\n";
      llvm::outs() << "  if (!sexp_cpointerp(arg0) && !sexp_not(arg0))\n";
      llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg0);\n";
      if (isIntegerLike(fieldType)) {
        llvm::outs() << "  if (!sexp_exact_integerp(arg1))\n";
        llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg1);\n";
      } else if (isCString(fieldType)) {
        llvm::outs() << "  if (!sexp_stringp(arg1) && !sexp_not(arg1))\n";
        llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_STRING, arg1);\n";
      } else if (isSupportedPointer(fieldType)) {
        llvm::outs() << "  if (!sexp_cpointerp(arg1) && !sexp_not(arg1))\n";
        llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg1);\n";
      }
      llvm::outs() << "  " << recordType << " *ptr = (" << recordType
                   << " *)sexp_cpointer_maybe_null_value(arg0);\n";
      llvm::outs() << "  if (ptr)\n";
      llvm::outs() << "    ptr->" << field->getNameAsString() << " = "
                   << fromSexpExpr(fieldType, "arg1") << ";\n";
      llvm::outs() << "  return SEXP_VOID;\n";
      llvm::outs() << "}\n\n";
      appendForeignRegistration(writerName, writerStubName, "SEXP_VOID",
                                {"sexp_make_fixnum(SEXP_CPOINTER)",
                                 schemeTypeIdExpr(fieldType)});
    }
  }

  void emitEnumConstants(const EnumDecl *decl) {
    if (!decl->isCompleteDefinition() || decl->getName().empty())
      return;
    std::string enumKey = "enum:" + toSymbol(decl->getQualifiedNameAsString());
    if (emitted.find(enumKey) != emitted.end())
      return;
    emitted.insert(enumKey);

    for (const EnumConstantDecl *item : decl->enumerators()) {
      if (!item || item->getName().empty())
        continue;
      std::string name = item->getNameAsString();
      constantDefinitions.push_back(
          "  sexp_env_define(ctx, env, sexp_intern(ctx, \"" + name +
          "\", -1), sexp_make_integer(ctx, (sexp_sint_t)" + name + "));\n");
    }
  }

  void emitDirectWrapper(const FunctionDecl *decl, const std::string &name) {
    const FunctionProtoType *ft = decl->getType()->getAs<FunctionProtoType>();
    llvm::outs() << "static sexp\nsexp_" << name << "_stub(sexp ctx, sexp self, sexp_sint_t n";
    for (unsigned i = 0; i < ft->getNumParams(); ++i)
      llvm::outs() << ", sexp arg" << i;
    llvm::outs() << ")\n{\n";
    for (unsigned i = 0; i < ft->getNumParams(); ++i) {
      QualType pt = canonicalType(ft->getParamType(i));
      std::string cty = cType(pt);
      if (isBool(pt)) {
        llvm::outs() << "  " << cty << " __param_" << i << " = !sexp_not(arg" << i << ");\n";
      } else if (isIntegerLike(pt)) {
        llvm::outs() << "  if (!sexp_exact_integerp(arg" << i
                     << ")) return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg"
                     << i << ");\n";
        llvm::outs() << "  " << cty << " __param_" << i << " = "
                     << fromSexpExpr(pt, "arg" + std::to_string(i)) << ";\n";
      } else if (isCString(pt)) {
        llvm::outs() << "  if (!sexp_stringp(arg" << i << ") && !sexp_not(arg"
                     << i
                     << ")) return sexp_type_exception(ctx, self, SEXP_STRING, arg"
                     << i << ");\n";
        llvm::outs() << "  " << cty << " __param_" << i << " = "
                     << fromSexpExpr(pt, "arg" + std::to_string(i)) << ";\n";
      } else if (isSupportedPointer(pt)) {
        llvm::outs() << "  if (!sexp_cpointerp(arg" << i << ") && !sexp_not(arg"
                     << i
                     << ")) return sexp_type_exception(ctx, self, SEXP_CPOINTER, arg"
                     << i << ");\n";
        llvm::outs() << "  " << cty << " __param_" << i << " = "
                     << fromSexpExpr(pt, "arg" + std::to_string(i)) << ";\n";
      }
    }

    if (isVoid(ft->getReturnType())) {
      llvm::outs() << "  " << name << "(";
    } else {
      llvm::outs() << "  " << cType(ft->getReturnType()) << " result = " << name
                   << "(";
    }
    for (unsigned i = 0; i < ft->getNumParams(); ++i) {
      if (i)
        llvm::outs() << ", ";
      llvm::outs() << "__param_" << i;
    }
    llvm::outs() << ");\n";
    if (isVoid(ft->getReturnType()))
      llvm::outs() << "  return SEXP_VOID;\n";
    else
      llvm::outs() << "  return " << toSexpExpr(ft->getReturnType(), "result")
                   << ";\n";
    llvm::outs() << "}\n\n";
    appendForeignRegistration(name, ft->getReturnType(), ft);
  }

  void emitHookSetter(const FunctionDecl *decl, const std::string &name,
                      const FunctionType *cbType) {
    std::string procVar = "g_" + name + "_proc";
    std::string cbName = "mockoto_chibi_cb_" + name;
    const FunctionProtoType *cbProto = dyn_cast<FunctionProtoType>(cbType);
    unsigned cbParamCount = cbProto ? cbProto->getNumParams() : 0;
    std::vector<int> lengthParamIndex(cbParamCount, -1);
    llvm::outs() << "static sexp " << procVar << " = SEXP_FALSE;\n\n";

    for (unsigned i = 0; i < cbParamCount; ++i) {
      if (isByteBufferPointer(cbProto->getParamType(i))) {
        for (unsigned j = i + 1; j < cbParamCount; ++j) {
          if (isIntegerLike(cbProto->getParamType(j))) {
            lengthParamIndex[i] = (int)j;
            break;
          }
        }
      }
    }

    llvm::outs() << "static " << cType(cbType->getReturnType()) << "\n";
    llvm::outs() << cbName << "(";
    for (unsigned i = 0; i < cbParamCount; ++i) {
      if (i)
        llvm::outs() << ", ";
      llvm::outs() << cType(cbProto->getParamType(i)) << " __param_" << i;
    }
    if (cbParamCount == 0)
      llvm::outs() << "void";
    llvm::outs() << ")\n{\n";
    bool needsResult = !isVoid(cbType->getReturnType());
    llvm::outs() << "  sexp args = SEXP_NULL;\n";
    if (needsResult)
      llvm::outs() << "  sexp result = SEXP_VOID;\n";
    llvm::outs() << "  if (sexp_not(" << procVar << "))";
    if (isVoid(cbType->getReturnType()))
      llvm::outs() << " return;\n";
    else
      llvm::outs() << " return (" << cType(cbType->getReturnType()) << ")("
                   << defaultReturnExpr(cbType->getReturnType()) << ");\n";

    for (int i = (int)cbParamCount - 1; i >= 0; --i) {
      llvm::outs() << "  args = sexp_cons(mockoto_chibi_ctx, "
                   << hookArgToSexpExpr(cbProto, lengthParamIndex, i,
                                        "__param_" + std::to_string(i))
                   << ", args);\n";
    }
    if (needsResult)
      llvm::outs() << "  result = sexp_apply(mockoto_chibi_ctx, " << procVar
                   << ", args);\n";
    else
      llvm::outs() << "  sexp_apply(mockoto_chibi_ctx, " << procVar
                   << ", args);\n";
    if (needsResult) {
      if (isVoid(cbType->getReturnType())) {
        llvm::outs() << "  return;\n";
      } else {
        llvm::outs() << "  return "
                     << fromSexpExpr(cbType->getReturnType(), "result") << ";\n";
      }
    } else {
      llvm::outs() << "  return;\n";
    }
    llvm::outs() << "}\n\n";

    llvm::outs() << "static sexp\nsexp_" << name
                 << "_stub(sexp ctx, sexp self, sexp_sint_t n, sexp arg0)\n{\n";
    llvm::outs() << "  if (!sexp_stringp(arg0) && !sexp_not(arg0))\n";
    llvm::outs() << "    return sexp_type_exception(ctx, self, SEXP_STRING, arg0);\n";
    llvm::outs() << "  mockoto_chibi_ctx = ctx;\n";
    llvm::outs() << "  if (sexp_not(arg0)) {\n";
    llvm::outs() << "    " << procVar << " = SEXP_FALSE;\n";
    llvm::outs() << "    " << name << "(NULL);\n";
    llvm::outs() << "    return SEXP_VOID;\n";
    llvm::outs() << "  }\n";
    llvm::outs() << "  " << procVar
                 << " = mockoto_chibi_lookup_proc(ctx, sexp_string_data(arg0));\n";
    llvm::outs() << "  if (sexp_exceptionp(" << procVar << ")) return " << procVar
                 << ";\n";
    llvm::outs() << "  " << name << "(" << cbName << ");\n";
    llvm::outs() << "  return SEXP_VOID;\n";
    llvm::outs() << "}\n\n";

    foreignRegistrations.push_back("  op = sexp_define_foreign(ctx, env, \"" +
                                   name + "\", 1, sexp_" + name +
                                   "_stub);\n"
                                   "  if (sexp_opcodep(op)) {\n"
                                   "    sexp_opcode_return_type(op) = SEXP_VOID;\n"
                                   "    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_STRING);\n"
                                   "  }\n");
    std::string hookTarget = name;
    const std::string prefix = "mockoto_";
    const std::string suffix = "_hook";
    if (hookTarget.rfind(prefix, 0) == 0 &&
        hookTarget.size() > prefix.size() + suffix.size() &&
        hookTarget.compare(hookTarget.size() - suffix.size(), suffix.size(),
                           suffix) == 0) {
      hookTarget =
          hookTarget.substr(prefix.size(),
                            hookTarget.size() - prefix.size() - suffix.size());
    }
    hookDispatches.push_back("  if (strcmp(hook, \"" + hookTarget +
                             "\") == 0)\n"
                             "    return sexp_" +
                             name + "_stub(ctx, self, 1, proc_name);\n");
  }

  void appendForeignRegistration(const std::string &name, QualType returnType,
                                 const FunctionProtoType *ft) {
    std::vector<std::string> argTypeExprs;
    for (unsigned i = 0; i < ft->getNumParams(); ++i)
      argTypeExprs.push_back(schemeTypeIdExpr(ft->getParamType(i)));
    appendForeignRegistration(name, schemeTypeIdExpr(returnType), argTypeExprs);
  }

  void appendForeignRegistration(const std::string &name,
                                 const std::string &stubName,
                                 const std::string &returnTypeExpr,
                                 const std::vector<std::string> &argTypeExprs) {
    std::string s = "  op = sexp_define_foreign(ctx, env, \"" + name + "\", " +
                    std::to_string(argTypeExprs.size()) + ", sexp_" + stubName +
                    "_stub);\n";
    s += "  if (sexp_opcodep(op)) {\n";
    s += "    sexp_opcode_return_type(op) = " + returnTypeExpr + ";\n";
    if (argTypeExprs.size() >= 1)
      s += "    sexp_opcode_arg1_type(op) = " + argTypeExprs[0] + ";\n";
    if (argTypeExprs.size() >= 2)
      s += "    sexp_opcode_arg2_type(op) = " + argTypeExprs[1] + ";\n";
    if (argTypeExprs.size() >= 3)
      s += "    sexp_opcode_arg3_type(op) = " + argTypeExprs[2] + ";\n";
    if (argTypeExprs.size() > 3) {
      s += "    sexp_opcode_argn_type(op) = sexp_make_vector(ctx, "
           "sexp_make_fixnum(" +
           std::to_string(argTypeExprs.size() - 3) +
           "), sexp_make_fixnum(SEXP_OBJECT));\n";
      for (unsigned i = 3; i < argTypeExprs.size(); ++i) {
        s += "    sexp_vector_set(sexp_opcode_argn_type(op), sexp_make_fixnum(" +
             std::to_string(i - 3) + "), " + argTypeExprs[i] +
             ");\n";
      }
    }
    s += "  }\n";
    foreignRegistrations.push_back(s);
  }

  void appendForeignRegistration(const std::string &name,
                                 const std::string &returnTypeExpr,
                                 const std::vector<std::string> &argTypeExprs) {
    appendForeignRegistration(name, name, returnTypeExpr, argTypeExprs);
  }
};

} // namespace mockoto

#endif
