#ifndef MOCKOTO_CONFIG_HPP
#define MOCKOTO_CONFIG_HPP

#include "version.h"

#include <list>
#include <string>

namespace mockoto {

inline const char *version() { return MOCKOTO_VERSION; }

inline std::string autogeneratedWarning(const std::string &commentPrefix) {
  return commentPrefix + " WARNING: file autogenerated with mockoto " +
         std::string(version()) + ". Changes will be lost.";
}

class Config {
public:
  enum Mode {
    MOCK_C,
    MOCK_H,
    BIND_RKT,
    BIND_CHIBI,
  } mode;

  Config(std::list<std::string> excludePatterns, Mode mode)
      : mode(mode), excludePatterns(excludePatterns), printSourcePath(false),
        includeStaticFunctions(false) {}

  const std::list<std::string> excludePatterns;
  std::list<std::string> includeFiles;

  bool printSourcePath; //< print source path of each generated mock or binding
  bool includeStaticFunctions;
};

} // namespace mockoto

#endif
